<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-07 at 03:55:02.
 */
class Database_Orientdb_ConnectionTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var Database_Orientdb_Connection
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		// $this->object = new Database_Orientdb_Connection;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Fuel\Core\Database_Orientdb_Connection::connect
	 * @todo   Implement testConnect().
	 */
	public function testConnect()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Fuel\Core\Database_Orientdb_Connection::disconnect
	 * @todo   Implement testDisconnect().
	 */
	public function testDisconnect()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Fuel\Core\Database_Orientdb_Connection::set_charset
	 * @todo   Implement testSet_charset().
	 */
	public function testSet_charset()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Fuel\Core\Database_Orientdb_Connection::query
	 * @todo   Implement testQuery().
	 */
	public function testQuery()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Fuel\Core\Database_Orientdb_Connection::list_tables
	 * @todo   Implement testList_tables().
	 */
	public function testList_tables()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Fuel\Core\Database_Orientdb_Connection::list_columns
	 * @todo   Implement testList_columns().
	 */
	public function testList_columns()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Fuel\Core\Database_Orientdb_Connection::escape
	 * @todo   Implement testEscape().
	 */
	public function testEscape()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Fuel\Core\Database_Orientdb_Connection::in_transaction
	 * @todo   Implement testIn_transaction().
	 */
	public function testIn_transaction()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Fuel\Core\Database_Orientdb_Connection::start_transaction
	 * @todo   Implement testStart_transaction().
	 */
	public function testStart_transaction()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Fuel\Core\Database_Orientdb_Connection::commit_transaction
	 * @todo   Implement testCommit_transaction().
	 */
	public function testCommit_transaction()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Fuel\Core\Database_Orientdb_Connection::rollback_transaction
	 * @todo   Implement testRollback_transaction().
	 */
	public function testRollback_transaction()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
